# Playbook to restart the nginx server
- name: Restart Nginx
  hosts: localhost
  gather_facts: yes
  become: true
  tasks:
    - name: Get the nginx process details
      ansible.builtin.systemd_service:
        name: nginx
      register: nginx_info

    - name: Log the process info
      debug:
        msg: "{{ nginx_info }}"

    - name: Restart Nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: started
      register: output

    - name: Log the output
      debug:
        msg: "{{ output }}"