- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Restart gunicorn service
  ansible.builtin.service:
    name: gunicorn
    state: restarted
    enabled: yes
  become: true