system_packages:
  - python3-apt
  - python3
  - python3-pip
  - python3-setuptools
  - python3-dev
  - build-essential
  - pkg-config
  - default-libmysqlclient-dev
  - python3-mysqldb
  - git
  - neovim


db_packages:
  - mysql-server
  - mysql-client

mysql:
  db: shop
  user: shop_admin
  password: "{{ mysql_password }}"
source_code:
  repo_url:  "https://github.com/eswarmaganti/flask-shop-app.git"
  branch_name: "main"